[tools]
cosign = "3.0.5"
"pipx:yamllint" = "1.38.0"
actionlint = "1.7.11"
shellcheck = "0.11.0"

[env]
REGISTRY = "ghcr.io/clemak27"
IMAGE_TAG = "latest"

[tasks.lint]
run = """
yamllint .
actionlint
shellcheck build.sh
shellcheck plasma.sh
"""

[tasks.build-image]
alias = "build-image-dankfedora"
run = """
docker build -t ${REGISTRY}/dankfedora:${IMAGE_TAG} . -f ./Containerfile.dankfedora
"""

[tasks.build-image-deck]
run = """
docker build -t ${REGISTRY}/dankydeck:${IMAGE_TAG} . -f ./Containerfile.dankydeck
"""
